version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "website"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@mrcomputer1/post-count-progress-bar" # Currently, updates will be handled manually.